#! /usr/bin/env sh

# Credits for Bash and Powershell in one "https://stackoverflow.com/questions/39421131/is-it-possible-to-write-one-script-that-runs-in-bash-shell-and-powershell"

# Starts multi-line string in Bash without printing anything
echo --% >/dev/null;: ' | out-null

cd ..
$PSDefaultParameterValues = @{"Out-File:Encoding" = "ASCII"}

function cpy([String]$1) {
<#' # Terminates Bash string and starts Powershell multi-line comment

cd "$(dirname $0)/.."

cpy() {
#> # Terminates Powershell multi-line comment
	echo "Copying $PWD/$1 to $PWD/arduino/src/$1"
	cp $PWD/$1 $PWD/arduino/src/$1
}

echo "Creating directory $PWD/arduino/src"
mkdir $PWD/arduino/src
mkdir $PWD/arduino/src/core
mkdir $PWD/arduino/src/firmware
echo "Generating $PWD/arduino/src/firmware/user_config.h"
echo '#include "../../user_config.h"' > $PWD/arduino/src/firmware/user_config.h
cpy core/atem.c
cpy core/atem.h
cpy core/atem_protocol.h
cpy firmware/atem_sock.c
cpy firmware/atem_sock.h
cpy firmware/debug.h
cpy firmware/dns.c
cpy firmware/dns.h
cpy firmware/flash.c
cpy firmware/flash.h
cpy firmware/http.c
cpy firmware/http.h
cpy firmware/http_respond.c
cpy firmware/http_respond.h
cpy firmware/i2c.h
cpy firmware/init.c
cpy firmware/init.h
cpy firmware/led.h
cpy firmware/sdi.c
cpy firmware/sdi.h
echo "Installed"
