#include <stdio.h> // printf
#include <stdlib.h> // atoi
#include <stdbool.h> // true, false

struct cache_wlan {
	char* ssid;
	char* psk;
	char* name;
};

#define CACHE_SSID wlan.ssid
#define CACHE_PSK wlan.psk
#define CACHE_NAME wlan.name

// Forces ip addresses in config_t to use type string instead of uint32_t since we are only printing anyway
#define uint32_t char*

#include "../../firmware/init.h" // FIRMWARE_VERSION_STRING
#include "../../firmware/flash.h" // CONF_FLAG_DHCP, struct cache_t

#define HTTP_RESPONSE_STATE_NONE (0)
#define HTTP_RESPONSE_STATE_ROOT (0)
#define HTTP_RESPONSE_STATE_POST_ROOT (1)

#define HTTP_RESPONSE_CASE(args) printf args;
#define HTTP_RESPONSE_CASE_STR(http, str) printf("%s", str);

#define http_write_value_string(http, str, len) ("%s", str)
#define http_write_value_uint8(http, value) ("%d", value)
#define http_write_value_addr(http, addr) ("%s", addr)
#define http_write_uptime(http) ("%s", UPTIME)
#define http_write_wifi(http) ("%s", WIFI_STATUS)

#define http_reboot(http)
#define atem_state (ATEM_STATUS)
#define http (&_http)
#define atem (_http.cache.config)

struct {
	struct cache_t cache;
	int responseState;
} _http = {
	.cache = {
		.config.atemAddr  = ATEM_ADDR,
		.config.dest      = DEST,
		.config.flags     = CONF_FLAG_DHCP & DHCP,
		.config.localAddr = LOCAL_ADDR,
		.config.netmask   = NETMASK,
		.config.gateway   = GATEWAY,
		.wlan.ssid        = SSID,
		.wlan.psk         = PSK,
		.wlan.name        = DEVICE_NAME
	}
};

// Entry function `main.c` is generated by `generate.sh` and appended to the end of this file when building
